<a href="https://colab.research.google.com/github/nxxk23/PROJECT/blob/main/Outlier/impute_binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/ckdresearch2023/Assign/Assign7: Outliers/data_not_rmfeatures.csv')
df = df.iloc[:, 1:]
df.head()

,PatientUID,PatientVisitUID,Slopes,G1M2:ARB,G3M1:Statin,G5M2:NSAIDs,G1M5:Diuretic,G1M7:Beta blocker,G1M3:Dihydropyridine CCB,G1M6:MRA,...,L27:UrineAlbumin/Cr ratio,L28:UrineProtein/Cr ratio,L29:UrineVolume (24hrs),L30:UrineUrea (24hrs),L31:UrineSodium (24hrs),L32:UrineProtein (24hrs),eGFR_t1,time_t1,LabLocation,LabCwhen
0,2299,3386255,-7.158596,90,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,63.60,2017-10-03 09:19:54.710,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,2559-08-15 09:51:55.203
1,2299,4546471,5.550691,90,90,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,70.20,2018-12-12 09:18:49.913,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,2560-10-03 09:19:54.920
2,2299,5812902,-6.063710,100,100,34,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,64.02,2019-12-19 09:51:24.427,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,2561-12-12 10:15:36.930
3,2299,6947220,-12.812245,35,0,1,35,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,48.54,2021-03-04 10:01:42.113,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,2562-12-19 09:51:24.577
4,2299,8186767,28.287500,100,0,15,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,80.47,2022-04-21 08:45:54.580,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,2564-03-04 10:07:37.037

In [3]:
data = pd.DataFrame(df)

In [4]:
# Find columns with null values in data
columns_with_null = data.columns[data.isnull().any()].tolist()

# Find columns to keep in data
columns_to_keep = [col for col in data.columns if col not in columns_with_null]

# Display the original order of columns
print("Original order of columns in data:")
print(data.columns.tolist())

# Display columns with null values and columns to keep
print("\nColumns with null values:")
print(columns_with_null)
print("\nColumns to keep:")
print(columns_to_keep)

Original order of columns in data:
['PatientUID', 'PatientVisitUID', 'Slopes', 'G1M2:ARB', 'G3M1:Statin', 'G5M2:NSAIDs', 'G1M5:Diuretic', 'G1M7:Beta blocker', 'G1M3:Dihydropyridine CCB', 'G1M6:MRA', 'G1M1:ACEI', 'G2M2:Metformin', 'G2M3:DPP4 inhibitor', 'G2M1:SU', 'G3M3:Fibrate', 'G2M5:SGLT2i', 'G4M1:Allopurinol', 'G1M9:Vasodilator', 'G1M8:Alpha blocker', 'G2M6:Insulin', 'G2M4:TZD', 'G4M2:Febuxostat', 'G3M2:Ezetimibe', 'G1M4:Non-dihydropyridine CCB', 'G5M1:Ketoanalog amino acid', 'G2M7:GLP1-RA', 'G4M3:Uricosuric agent', 'Sex', 'Age', 'NATNL', 'VisitLocation', 'StartDTTM', 'EndDttm', 'InPatient', 'OutPatient', 'Emergency', 'BMI', 'BSA', 'Diastolic BP', 'Systolic BP', 'D1:Hypertension', 'D2:Diabetes mellitus', 'D3:Dyslipidemia', 'D4:SLE', 'D5:Systemic sclerosis', 'D6:Rheumatoid arthritis', 'D7:HIV infection', 'D8:HBV infection', 'D9:HCV infection', 'D10:Ischemic heart disease', 'D11:Heart failure', 'D12:Thalassemia', 'D13:Kidney stone', 'D14:Valvular heart disease', 'D15:Solid malignancy', 'D16:Hematologic malignancy', 'L1:eGFR', 'L2:BUN', 'L3:Creatinine', 'L4:Sodium', 'L5:Potassium', 'L6:Chloride', 'L7:Bicarbonate', 'L8:Uric', 'L9:Calcium', 'L10:Phosphorus', 'L11:Albumin', 'L12:Hemoglobin', 'L13:Hematocrit', 'L14:WBC', 'L15:Platelet', 'L16:TIBC', 'L17:Tranferin SAT', 'L18:Ferritin', 'L19:Blood sugar', 'L20:HbA1c', 'L21:Cholesterol', 'L22:Triglyceride', 'L23:LDL Cholesterol', 'L24:HDL Cholesterol', 'L25:Parathyroid hormone', 'L26:Vitamin D', 'L27:UrineAlbumin/Cr ratio', 'L28:UrineProtein/Cr ratio', 'L29:UrineVolume (24hrs)', 'L30:UrineUrea (24hrs)', 'L31:UrineSodium (24hrs)', 'L32:UrineProtein (24hrs)', 'eGFR_t1', 'time_t1', 'LabLocation', 'LabCwhen']

Columns with null values:
['BMI', 'BSA', 'Diastolic BP', 'Systolic BP', 'L1:eGFR', 'L2:BUN', 'L3:Creatinine', 'L4:Sodium', 'L5:Potassium', 'L6:Chloride', 'L7:Bicarbonate', 'L8:Uric', 'L9:Calcium', 'L10:Phosphorus', 'L11:Albumin', 'L12:Hemoglobin', 'L13:Hematocrit', 'L14:WBC', 'L15:Platelet', 'L16:TIBC', 'L17:Tranferin SAT', 'L18:Ferritin', 'L19:Blood sugar', 'L20:HbA1c', 'L21:Cholesterol', 'L22:Triglyceride', 'L23:LDL Cholesterol', 'L24:HDL Cholesterol', 'L25:Parathyroid hormone', 'L26:Vitamin D', 'L27:UrineAlbumin/Cr ratio', 'L28:UrineProtein/Cr ratio', 'L29:UrineVolume (24hrs)', 'L30:UrineUrea (24hrs)', 'L31:UrineSodium (24hrs)', 'L32:UrineProtein (24hrs)']

Columns to keep:
['PatientUID', 'PatientVisitUID', 'Slopes', 'G1M2:ARB', 'G3M1:Statin', 'G5M2:NSAIDs', 'G1M5:Diuretic', 'G1M7:Beta blocker', 'G1M3:Dihydropyridine CCB', 'G1M6:MRA', 'G1M1:ACEI', 'G2M2:Metformin', 'G2M3:DPP4 inhibitor', 'G2M1:SU', 'G3M3:Fibrate', 'G2M5:SGLT2i', 'G4M1:Allopurinol', 'G1M9:Vasodilator', 'G1M8:Alpha blocker', 'G2M6:Insulin', 'G2M4:TZD', 'G4M2:Febuxostat', 'G3M2:Ezetimibe', 'G1M4:Non-dihydropyridine CCB', 'G5M1:Ketoanalog amino acid', 'G2M7:GLP1-RA', 'G4M3:Uricosuric agent', 'Sex', 'Age', 'NATNL', 'VisitLocation', 'StartDTTM', 'EndDttm', 'InPatient', 'OutPatient', 'Emergency', 'D1:Hypertension', 'D2:Diabetes mellitus', 'D3:Dyslipidemia', 'D4:SLE', 'D5:Systemic sclerosis', 'D6:Rheumatoid arthritis', 'D7:HIV infection', 'D8:HBV infection', 'D9:HCV infection', 'D10:Ischemic heart disease', 'D11:Heart failure', 'D12:Thalassemia', 'D13:Kidney stone', 'D14:Valvular heart disease', 'D15:Solid malignancy', 'D16:Hematologic malignancy', 'eGFR_t1', 'time_t1', 'LabLocation', 'LabCwhen']

**Add One Binary Variable**

In [5]:
import numpy as np

for col in columns_with_null:
    data['new' + col] = np.where(data[col].isnull(), 1, 0)

In [6]:
# Select columns that start with 'new'
new_columns = [col for col in data.columns if col.startswith('new')]

# Select columns with null values and 'new' columns
selected_columns = columns_with_null + new_columns

##**impute**


```
* Mode = If the data type is 'object'.
* Mean = If the data type is numeric (not 'object') and dont have outlier
* Median = If the data type is numeric (not 'object') and have outlier

```

In [7]:
missing_for_binary = pd.concat([data[columns_to_keep], data[columns_with_null]], axis=1)

In [8]:
imputed_table = missing_for_binary.copy()

In [9]:
# Print information before imputation
print("Null values before imputation:")
print(imputed_table[columns_with_null].isnull().sum())

Null values before imputation:
BMI                          15339
BSA                          15349
Diastolic BP                  6842
Systolic BP                   6801
L1:eGFR                          1
L2:BUN                       12840
L3:Creatinine                    1
L4:Sodium                    21283
L5:Potassium                 19019
L6:Chloride                  21364
L7:Bicarbonate               21204
L8:Uric                      38898
L9:Calcium                   40444
L10:Phosphorus               40779
L11:Albumin                  29910
L12:Hemoglobin               23612
L13:Hematocrit               22310
L14:WBC                      22314
L15:Platelet                 22314
L16:TIBC                     51736
L17:Tranferin SAT            51851
L18:Ferritin                 51725
L19:Blood sugar              23303
L20:HbA1c                    27985
L21:Cholesterol              18974
L22:Triglyceride             26220
L23:LDL Cholesterol          23395
L24:HDL Cholesterol          26626
L25:Parathyroid hormone      51737
L26:Vitamin D                51350
L27:UrineAlbumin/Cr ratio    51316
L28:UrineProtein/Cr ratio    47152
L29:UrineVolume (24hrs)      52280
L30:UrineUrea (24hrs)        52224
L31:UrineSodium (24hrs)      52336
L32:UrineProtein (24hrs)     52109
dtype: int64

In [10]:
columns_with_outliers = ['L10:Phosphorus', 'L13:Hematocrit', 'L21:Cholesterol', 'L2:BUN', 'L4:Sodium', 'L6:Chloride', 'L7:Bicarbonate', 'L8:Uric', 'L9:Calcium']

# Check for outliers in each column and fill missing values accordingly
for column in columns_with_null:
    if column in columns_with_outliers:
        # Columns with outliers
        median_values_patient = imputed_table.groupby('PatientUID')[column].median()
        imputed_table[column].fillna(imputed_table['PatientUID'].map(median_values_patient), inplace=True)
    else:
        # Columns without outliers, use mean for each patient
        mean_values_patient = imputed_table.groupby('PatientUID')[column].mean()
        imputed_table[column].fillna(imputed_table['PatientUID'].map(mean_values_patient), inplace=True)

# Fill remaining missing values using overall mean (or median)
for column in columns_with_null:
    if imputed_table[column].isnull().any():
        if imputed_table[column].dtype == 'O':  # Check dtype for the specific column
            # Use overall mode for remaining missing values
            imputed_table[column].fillna(imputed_table[column].mode()[0], inplace=True)
        else:
            # Use overall mean for remaining missing values
            overall_mean = imputed_table[column].mean()
            imputed_table[column].fillna(overall_mean, inplace=True)

# Print information after imputation
print("\nNull values after imputation:")
print(imputed_table[columns_with_null].isnull().sum())

Null values after imputation:
BMI                          0
BSA                          0
Diastolic BP                 0
Systolic BP                  0
L1:eGFR                      0
L2:BUN                       0
L3:Creatinine                0
L4:Sodium                    0
L5:Potassium                 0
L6:Chloride                  0
L7:Bicarbonate               0
L8:Uric                      0
L9:Calcium                   0
L10:Phosphorus               0
L11:Albumin                  0
L12:Hemoglobin               0
L13:Hematocrit               0
L14:WBC                      0
L15:Platelet                 0
L16:TIBC                     0
L17:Tranferin SAT            0
L18:Ferritin                 0
L19:Blood sugar              0
L20:HbA1c                    0
L21:Cholesterol              0
L22:Triglyceride             0
L23:LDL Cholesterol          0
L24:HDL Cholesterol          0
L25:Parathyroid hormone      0
L26:Vitamin D                0
L27:UrineAlbumin/Cr ratio    0
L28:UrineProtein/Cr ratio    0
L29:UrineVolume (24hrs)      0
L30:UrineUrea (24hrs)        0
L31:UrineSodium (24hrs)      0
L32:UrineProtein (24hrs)     0
dtype: int64

In [11]:
# Select columns that start with 'new'
columns_with_new = [col for col in data.columns if col.startswith('new')]

# Merge the selected columns
merged_data = pd.concat([imputed_table, data[columns_with_new]], axis=1)
merged_data.head()

,PatientUID,PatientVisitUID,Slopes,G1M2:ARB,G3M1:Statin,G5M2:NSAIDs,G1M5:Diuretic,G1M7:Beta blocker,G1M3:Dihydropyridine CCB,G1M6:MRA,...,newL23:LDL Cholesterol,newL24:HDL Cholesterol,newL25:Parathyroid hormone,newL26:Vitamin D,newL27:UrineAlbumin/Cr ratio,newL28:UrineProtein/Cr ratio,newL29:UrineVolume (24hrs),newL30:UrineUrea (24hrs),newL31:UrineSodium (24hrs),newL32:UrineProtein (24hrs)
0,2299,3386255,-7.158596,90,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
1,2299,4546471,5.550691,90,90,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
2,2299,5812902,-6.063710,100,100,34,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
3,2299,6947220,-12.812245,35,0,1,35,0,0,0,...,0,0,1,1,1,1,1,1,1,1
4,2299,8186767,28.287500,100,0,15,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1

In [12]:
binary_columns = [col for col in merged_data.columns if col.startswith('new')]
#data.drop(binary_columns, axis=1, inplace=True)

In [16]:
merged_data

,PatientUID,PatientVisitUID,Slopes,G1M2:ARB,G3M1:Statin,G5M2:NSAIDs,G1M5:Diuretic,G1M7:Beta blocker,G1M3:Dihydropyridine CCB,G1M6:MRA,...,newL23:LDL Cholesterol,newL24:HDL Cholesterol,newL25:Parathyroid hormone,newL26:Vitamin D,newL27:UrineAlbumin/Cr ratio,newL28:UrineProtein/Cr ratio,newL29:UrineVolume (24hrs),newL30:UrineUrea (24hrs),newL31:UrineSodium (24hrs),newL32:UrineProtein (24hrs)
0,2299,3386255,-7.158596,90,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
1,2299,4546471,5.550691,90,90,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
2,2299,5812902,-6.063710,100,100,34,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
3,2299,6947220,-12.812245,35,0,1,35,0,0,0,...,0,0,1,1,1,1,1,1,1,1
4,2299,8186767,28.287500,100,0,15,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52615,3319961,9270330,-4.256753,100,100,0,0,0,0,0,...,0,0,1,1,0,0,1,1,1,1
52616,3319971,9270331,-0.692078,0,100,0,0,0,0,0,...,0,0,1,1,0,0,1,1,1,1
52617,3320048,9242721,7.217875,0,0,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,1
52618,3320050,9257281,-32.794557,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
52619,3321289,9274735,-36.776371,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

In [21]:
data = merged_data.copy()

In [22]:
# Splitting the 'time' column into separate columns
data[['date', 'timestamp']] = data['LabCwhen'].str.split(' ', expand=True)
data[['year', 'month', 'day']] = data['date'].str.split('-', expand=True)
data[['hour', 'minute', 'second']] = data['timestamp'].str.split(':', expand=True)
data[['second', 'nanosecond']] = data['second'].str.split('.', expand=True)

# Convert year column from BE to AD
data['year'] = data['year'].astype(int) - 543

# Combine columns into a datetime column
data['date'] = pd.to_datetime(data[['year', 'month', 'day',]])
# Convert timestamp to Timedelta
data['timestamp'] = pd.to_timedelta(data['timestamp'])

# Convert date to datetime
data['date'] = pd.to_datetime(data['date'])

# Merge timestamp and date columns
data['LabCwhen'] = data['date'] + data['timestamp']

columns_to_drop = ['date', 'timestamp', 'year', 'month', 'day', 'hour', 'minute', 'second', 'nanosecond']
data = data.drop(columns=columns_to_drop, axis=1)

In [23]:
# Splitting the 'time' column into separate columns
data[['date', 'timestamp']] = data['StartDTTM'].str.split(' ', expand=True)
data[['year', 'month', 'day']] = data['date'].str.split('-', expand=True)
data[['hour', 'minute', 'second']] = data['timestamp'].str.split(':', expand=True)
data[['second', 'nanosecond']] = data['second'].str.split('.', expand=True)

# Convert year column from BE to AD
data['year'] = data['year'].astype(int) - 543

# Combine columns into a datetime column
data['date'] = pd.to_datetime(data[['year', 'month', 'day',]])
# Convert timestamp to Timedelta
data['timestamp'] = pd.to_timedelta(data['timestamp'])

# Convert date to datetime
data['date'] = pd.to_datetime(data['date'])

# Merge timestamp and date columns
data['StartDTTM'] = data['date'] + data['timestamp']

columns_to_drop = ['date', 'timestamp', 'year', 'month', 'day', 'hour', 'minute', 'second', 'nanosecond']
data = data.drop(columns=columns_to_drop, axis=1)

In [24]:
# Splitting the 'time' column into separate columns
data[['date', 'timestamp']] = data['EndDttm'].str.split(' ', expand=True)
data[['year', 'month', 'day']] = data['date'].str.split('-', expand=True)
data[['hour', 'minute', 'second']] = data['timestamp'].str.split(':', expand=True)
data[['second', 'nanosecond']] = data['second'].str.split('.', expand=True)

# Convert year column from BE to AD
data['year'] = data['year'].astype(int) - 543

# Combine columns into a datetime column
data['date'] = pd.to_datetime(data[['year', 'month', 'day',]])
# Convert timestamp to Timedelta
data['timestamp'] = pd.to_timedelta(data['timestamp'])

# Convert date to datetime
data['date'] = pd.to_datetime(data['date'])

# Merge timestamp and date columns
data['EndDttm'] = data['date'] + data['timestamp']

columns_to_drop = ['date', 'timestamp', 'year', 'month', 'day', 'hour', 'minute', 'second', 'nanosecond']
data = data.drop(columns=columns_to_drop, axis=1)

In [25]:
data[['LabCwhen','time_t1','StartDTTM','EndDttm']]

,LabCwhen,time_t1,StartDTTM,EndDttm
0,2016-08-15 09:51:55.203,2017-10-03 09:19:54.710,2016-08-15 08:13:26.043,2016-08-16 05:01:01.473
1,2017-10-03 09:19:54.920,2018-12-12 09:18:49.913,2017-10-03 07:37:22.777,2017-10-04 05:01:01.903
2,2018-12-12 10:15:36.930,2019-12-19 09:51:24.427,2018-12-12 07:58:57.190,2018-12-13 05:01:01.250
3,2019-12-19 09:51:24.577,2021-03-04 10:01:42.113,2019-12-19 08:19:38.647,2019-12-20 05:01:01.910
4,2021-03-04 10:07:37.037,2022-04-21 08:45:54.580,2021-03-04 07:55:40.703,2021-03-05 05:01:01.240
...,...,...,...,...
52615,2022-03-14 15:10:29.530,2023-04-04 08:28:58.833,2022-03-14 14:31:31.910,2022-03-15 05:01:01.450
52616,2022-03-14 15:45:26.500,2023-04-04 08:49:20.047,2022-03-14 14:31:53.720,2022-03-15 05:01:01.450
52617,2022-03-05 17:34:10.677,2023-04-10 08:36:15.217,2022-03-05 12:36:33.263,2022-03-06 05:01:02.833
52618,2022-03-10 11:13:28.003,2023-04-10 08:58:57.267,2022-03-10 07:42:44.243,2022-03-11 05:01:01.390
52619,2022-03-15 23:56:03.070,2023-04-03 09:58:08.837,2022-03-15 13:28:12.177,2022-03-21 15:31:28.463

In [26]:
data['LabLocation'] = np.where(data['LabLocation'] == "ห้องปฏิบัติการจุลทรรศน์วินิจฉัย", 1, 0)
data['LabLocation'].value_counts()

1    26916
0    25704
Name: LabLocation, dtype: int64

In [28]:
nationality_map = {'ไทย': 0}

caucasian = ['บริติช  (อังกฤษ, สก็อตแลนด์)', 'อเมริกัน', 'เยอรมัน', 'โอมาน', 'ออสเตรเลีย', 'แคนาดา',
             'อิตาลี', 'สวิส', 'ซีเรีย', 'เดนมาร์ก', 'นอร์เวย์', 'ดัตช์', 'สเปน', 'เบลเยียม', 'ไอซ์แลนด์',
             'ฝรั่งเศส', 'เซนต์คิตส์และเนวิส', 'สวีเดน', 'ออสเตรีย', 'ไซปรัส']
asian = ['ลาว','จีน','เวียดนาม','เขมรอพยพ','ไทยลื้อ','ญี่ปุ่น', 'จีน(ไต้หวัน)']
other = ['ไม่ระบุ','อื่นๆ','ไร้สัญชาติ']

for nationality in asian:
    nationality_map[nationality] = 1

for nationality in caucasian:
    nationality_map[nationality] = 2

for nationality in other:
    nationality_map[nationality] = 3

data['NATNL'] = data['NATNL'].replace(nationality_map)

In [29]:
data['NATNL'] = data['NATNL'].replace({0: 'Asian', 1: 'Asian', 3: 'Asian', 2: 'Non-Asian'})
data['NATNL'].value_counts()

Asian        52447
Non-Asian      173
Name: NATNL, dtype: int64

In [31]:
data['Sex'] = data['Sex'].replace({'ชาย': 0, 'หญิง': 1})

```
ตอนแรกมี 92
มีคอลัมน์ with null 36 ==> binary (ขึ้นต้นด้วย new)
82 + 36 = 128
```

In [34]:
data.to_excel('outlier_binary.xlsx')