<a href="https://colab.research.google.com/github/nxxk23/PROJECT/blob/main/LabWBC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
hemo = pd.read_csv('/content/drive/MyDrive/Thesis Project Kidney/Hemodialysis.csv', encoding='latin1')
lab = pd.read_csv('/content/drive/MyDrive/Thesis Project Kidney/Lab.csv')

In [3]:
patient_uid_list = hemo['PatientUID'].unique().tolist()

In [4]:
# Remove patient UIDs from lab['PatientUID'] that are not in the list
lab = lab[~lab['PatientUID'].isin(patient_uid_list)]

## **WBC**

In [5]:
selected_rows = lab[lab['ResultItemName'].notna() & lab['ResultItemName'].str.startswith('WBC')]
selected_rows

,LabNo,PatientUID,PatientVisitUID,Location,RequestItemName,ResultItemName,CWhen,ResultDttm,ResultValue,Unit,ReferenceRange
76,1,2299,2381054,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Urinalysis,WBC,2558-07-17 11:25:30.333,NaN,-,NaN,NaN
101,1,2299,2499619,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Urinalysis,WBC,2558-09-03 16:02:57.063,NaN,0 - 1 / HPF,NaN,NaN
177,1,2299,3169528,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Complete blood count,WBC,2559-05-25 10:22:10.790,2559-08-15 11:32:08.407,5.40,10^3/uL,NaN
242,1,2299,3373017,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Urinalysis,WBC,2559-08-09 11:08:58.213,NaN,-,NaN,NaN
313,1,2299,4286612,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Complete blood count,WBC,2560-07-05 10:53:36.177,NaN,5.52,10^3/uL,4.60 - 10.60
...,...,...,...,...,...,...,...,...,...,...,...
21628551,161,925649,3617725,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Complete blood count,WBC,2560-04-17 10:21:23.680,NaN,9.90,10^3/uL,4.60 - 10.60
21628788,162,925649,3617725,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Complete blood count,WBC,2560-04-19 09:43:43.067,NaN,9.70,10^3/uL,4.60 - 10.60
21629017,163,925649,3617725,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Complete blood count,WBC,2560-04-21 08:44:06.027,NaN,5.70,10^3/uL,4.60 - 10.60
21629239,164,925649,3617725,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Complete blood count,WBC,2560-04-24 11:24:30.027,NaN,7.00,10^3/uL,4.60 - 10.60
21629449,165,925649,3617725,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,Complete blood count,WBC,2560-04-26 11:31:00.160,NaN,6.30,10^3/uL,4.60 - 10.60

In [6]:
unique_values = selected_rows['ResultItemName'].unique() #5
mapping = {value: 'WBC' for value in unique_values}

# Replace the unique values with 'WBC'
selected_rows['ResultItemName'] = selected_rows['ResultItemName'].replace(mapping)

<ipython-input-6-bad4ad960582>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_rows['ResultItemName'] = selected_rows['ResultItemName'].replace(mapping)

In [7]:
lab.update(selected_rows)



> **เหลือต้องคลีน RequestItemName**

In [8]:
a = lab[lab['ResultItemName'].notna() & lab['ResultItemName'].str.startswith('WBC')]
a['ResultItemName'].unique() # check

array(['WBC'], dtype=object)

In [19]:
import pandas as pd

# Function to clean and group by keywords
def clean_and_group(item):
    if item.startswith("CD4"):
        return "CD4 count"
    elif item.startswith("Stool"):
        return "Stool examination"
    else:
        return item

# Modify the 'RequestItemName' column directly
lab['RequestItemName'] = lab['RequestItemName'].apply(clean_and_group)
lab['RequestItemName'] = lab['RequestItemName'].str.extract(r'^(.*?)( \(|$)')[0].str.strip()

In [25]:
lab['ResultItemName'].nunique()

1517

In [22]:
lab['RequestItemName'].nunique()

2088

In [23]:
lab_location = lab['Location'].value_counts().reset_index()
lab_location.columns = ['Location', 'Location_Count']

lab_result = lab['ResultItemName'].value_counts().reset_index()
lab_result.columns = ['ResultItemName', 'ResultItemName_Count']

lab_request = lab['RequestItemName'].value_counts().reset_index()
lab_request.columns = ['RequestItemName', 'RequestItemName_Count']

columns_to_count = ['Location', 'ResultItemName', 'RequestItemName']

# Count unique values in the specified columns
lab_count = lab[columns_to_count].value_counts().reset_index()
lab_count.columns = ['Location', 'ResultItemName', 'RequestItemName', 'Count']
lab_count

,Location,ResultItemName,RequestItemName,Count
0,ห้องปฏิบัติการเคมีคลินิก เวชศาสตร์ชันสูตร,"CREATININE, 32202",CREATININE,464626
1,ห้องปฏิบัติการเคมีคลินิก เวชศาสตร์ชันสูตร,eGFR(CKD-EPI) age >=18,CREATININE,435208
2,ห้องปฏิบัติการเคมีคลินิก เวชศาสตร์ชันสูตร,"POTASSIUM, 32103",POTASSIUM,399456
3,ห้องปฏิบัติการเคมีคลินิก เวชศาสตร์ชันสูตร,"BUN, 32201",BUN,388865
4,ห้องปฏิบัติการเคมีคลินิก เวชศาสตร์ชันสูตร,"BICARBONATE, 32105",BICARBONATE,386526
...,...,...,...,...
2985,ห้องปฏิบัติการภูมิคุ้มกันวิทยาคลินิก,"MUMP IGM, 36650",MUMP IGM,1
2986,ห้องปฏิบัติการภูมิคุ้มกันวิทยาคลินิก,"MUMP IGM, 36650","MUMP IGM, 36650",1
2987,ห้องปฏิบัติการภูมิคุ้มกันวิทยาคลินิก,Microsomal Ab,Microsomal Ab,1
2988,ห้องปฏิบัติการภูมิคุ้มกันวิทยาคลินิก,Mosquito,i71 Mosquito(Specific IgE),1
2989,ห้องปฏิบัติการภูมิคุ้มกันวิทยาคลินิก,FSH 120 min,FSH 120 min,1

In [26]:
b = lab_count[lab_count['ResultItemName'].notna() & lab_count['ResultItemName'].str.startswith('WBC')]
b

,Location,ResultItemName,RequestItemName,Count
12,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,WBC,Complete blood count,315233
42,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,WBC,Urinalysis,160864
201,ห้องปฏิบัติการภาควิชาปรสิตวิทยา,WBC,Stool examination,5416
250,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,WBC,Stool examination,2937
292,ห้องปฏิบัติการภาควิชาจุลชีววิทยา,WBC,CD4 count,1907
1142,ห้องปฏิบัติการจุลทรรศน์วินิจฉัย,WBC,Md Personnel Checkup stool examination,39
1927,ห้องปฏิบัติการภาควิชาจุลชีววิทยา,WBC,CD8 count,6
2050,ห้องปฏิบัติการภาควิชาจุลชีววิทยา,WBC,Urinalysis,5
2488,ห้องปฏิบัติการหน่วยชีวโมเลกุลวินัจฉัย,WBC,Urinalysis,2

In [27]:
lab_count.to_excel('LabFile.xlsx')