<a href="https://colab.research.google.com/github/nxxk23/PROJECT/blob/main/WideTable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

hemo = pd.read_csv('/content/drive/MyDrive/Thesis Project Kidney/Hemodialysis.csv', encoding='latin1')
# Create a list from hemo['PatientUID']
patient_uid_list = hemo['PatientUID'].unique().tolist()

In [3]:
import pandas as pd
vital = pd.read_csv('/content/drive/MyDrive/Thesis Project Kidney/vitalsign.csv')
# Remove patient UIDs from visit['PatientUID'] that are not in the list
vital = vital[~vital['PatientUID'].isin(patient_uid_list)]
vital['PatientUID'].nunique()

20714

In [4]:
visit = pd.read_csv('/content/drive/MyDrive/Thesis Project Kidney/Visit.csv')

# Remove patient UIDs from visit['PatientUID'] that are not in the list
visit = visit[~visit['PatientUID'].isin(patient_uid_list)]
visit['PatientUID'].nunique()

<ipython-input-4-3ec828bcbf86>:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  visit = pd.read_csv('/content/drive/MyDrive/Thesis Project Kidney/Visit.csv')

20967

In [5]:
import pandas as pd
lab = pd.read_csv('/content/drive/MyDrive/Thesis Project Kidney/Lab.csv')
# Remove patient UIDs from visit['PatientUID'] that are not in the list
lab = lab[~lab['PatientUID'].isin(patient_uid_list)]
lab['PatientUID'].nunique()

20967

In [6]:
slope = pd.read_excel("/content/drive/MyDrive/Thesis Project Kidney/Assign/Assign 3: Re-CountSlope & Quartile/LabSlope.xlsx")
slope['PatientUID'].nunique()

17711

In [7]:
diagnosis = pd.read_csv('/content/drive/MyDrive/Thesis Project Kidney/Diagnosis.csv')
# Remove patient UIDs from visit['PatientUID'] that are not in the list
diagnosis = diagnosis[~diagnosis['PatientUID'].isin(patient_uid_list)]
diagnosis['PatientUID'].nunique()

20719

## üóí**Note**
> **‡∏à‡∏≥‡∏ô‡∏ß‡∏ô‡∏ú‡∏π‡πâ‡∏õ‡πà‡∏ß‡∏¢‡πÉ‡∏ô‡πÅ‡∏ï‡πà‡∏•‡∏∞‡πÑ‡∏ü‡∏•‡πå (‡∏´‡∏•‡∏±‡∏á‡∏ï‡∏±‡∏î Hemo)**
- vital == 20714
- visit == 20976
- lab  == 20967
- diag == 20719
- slope == 17711

### **Test Vital**

In [8]:
vital['ResultItemName'].unique()

array(['Weight', 'BMI', 'Pulse Rate', 'Respiratory Rate', 'Systolic BP',
       'BSA', 'Diastolic BP', 'Height', 'Temperature', 'O2 Sat',
       'Pain Score', 'MeanPressure', 'Waistline', 'IrregularHeartBeat',
       'AverageMeasurement', '6MWT', 'Head Circumference', 'Fat'],
      dtype=object)

In [9]:
vital.columns

Index(['LabNo', 'PatientUID', 'PatientVisitUID', 'OrderItemName',
       'ResultItemName', 'ResultValue', 'CWhen'],
      dtype='object')

In [10]:
import pandas as pd

# Assuming 'vital' is a DataFrame containing your data
# Columns: ['LabNo', 'PatientUID', 'PatientVisitUID', 'OrderItemName', 'ResultItemName', 'ResultValue', 'CWhen']

# Use pivot_table if there are duplicate entries for the same 'ResultItemName' and 'ResultValue' combination
pivot_table = vital.pivot_table(index=['LabNo', 'PatientUID', 'PatientVisitUID', 'OrderItemName'], columns='ResultItemName', values='ResultValue', aggfunc='first')

# Use pivot if there are no duplicate entries for the same 'ResultItemName' and 'ResultValue' combination
pivot = vital.pivot(index=['LabNo', 'PatientUID', 'PatientVisitUID', 'OrderItemName'], columns='ResultItemName', values='ResultValue')


# Now, you have a wide-format DataFrame where 'ResultItemName' values become columns

In [11]:
pivot

ResultItemName                                      6MWT AverageMeasurement  \
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record  NaN                NaN
                 2024049         Vital Signs Record  NaN                NaN
                 2237669         Vital Signs Record  NaN                NaN
                 2396155         Vital Signs Record  NaN                NaN
                 2480434         Vital Signs Record  NaN                NaN
...                                                  ...                ...
1326  1472363    9805481         Vital Signs Record  NaN                NaN
1327  1472363    9805481         Vital Signs Record  NaN                NaN
1328  1472363    9805481         Vital Signs Record  NaN                NaN
1329  1472363    9805481         Vital Signs Record  NaN                NaN
1330  1472363    9805481         Vital Signs Record  NaN                NaN

ResultItemName                                         BMI   BSA Diastolic BP  \
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record  20.73  1.36           79
                 2024049         Vital Signs Record  20.17  1.39           65
                 2237669         Vital Signs Record  20.36  1.38           83
                 2396155         Vital Signs Record     20  1.37           67
                 2480434         Vital Signs Record  18.51  1.31           96
...                                                    ...   ...          ...
1326  1472363    9805481         Vital Signs Record    NaN   NaN          NaN
1327  1472363    9805481         Vital Signs Record    NaN   NaN          NaN
1328  1472363    9805481         Vital Signs Record    NaN   NaN          NaN
1329  1472363    9805481         Vital Signs Record    NaN   NaN          NaN
1330  1472363    9805481         Vital Signs Record    NaN   NaN          NaN

ResultItemName                                       Fat Head Circumference  \
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record  NaN                NaN
                 2024049         Vital Signs Record  NaN                NaN
                 2237669         Vital Signs Record  NaN                NaN
                 2396155         Vital Signs Record  NaN                NaN
                 2480434         Vital Signs Record  NaN                NaN
...                                                  ...                ...
1326  1472363    9805481         Vital Signs Record  NaN                NaN
1327  1472363    9805481         Vital Signs Record  NaN                NaN
1328  1472363    9805481         Vital Signs Record  NaN                NaN
1329  1472363    9805481         Vital Signs Record  NaN                NaN
1330  1472363    9805481         Vital Signs Record  NaN                NaN

ResultItemName                                      Height IrregularHeartBeat  \
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record    148                NaN
                 2024049         Vital Signs Record    151                NaN
                 2237669         Vital Signs Record    150                NaN
                 2396155         Vital Signs Record    150                NaN
                 2480434         Vital Signs Record    149                NaN
...                                                    ...                ...
1326  1472363    9805481         Vital Signs Record    NaN                NaN
1327  1472363    9805481         Vital Signs Record    NaN                NaN
1328  1472363    9805481         Vital Signs Record    NaN                NaN
1329  1472363    9805481         Vital Signs Record    NaN                NaN
1330  1472363    9805481         Vital Signs Record    NaN                NaN

ResultItemName                                      MeanPressure O2 Sat  \
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record          NaN    NaN
                 2024049         Vital Signs Record          NaN    NaN
                 2237669         Vital Signs Record          NaN    NaN
                 2396155         Vital Signs Record          NaN    NaN
                 2480434         Vital Signs Record          NaN    NaN
...                                                          ...    ...
1326  1472363    9805481         Vital Signs Record          NaN    NaN
1327  1472363    9805481         Vital Signs Record          NaN    NaN
1328  1472363    9805481         Vital Signs Record          NaN    NaN
1329  1472363    9805481         Vital Signs Record          NaN    NaN
1330  1472363    9805481         Vital Signs Record          NaN    NaN

ResultItemName                                      Pain Score Pulse Rate  \
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record        NaN         70
                 2024049         Vital Signs Record        NaN         73
                 2237669         Vital Signs Record        NaN         75
                 2396155         Vital Signs Record        NaN         76
                 2480434         Vital Signs Record        NaN         74
...                                                        ...        ...
1326  1472363    9805481         Vital Signs Record        NaN         92
1327  1472363    9805481         Vital Signs Record        NaN         92
1328  1472363    9805481         Vital Signs Record        NaN         92
1329  1472363    9805481         Vital Signs Record        NaN         91
1330  1472363    9805481         Vital Signs Record        NaN         91

ResultItemName                                      Respiratory Rate  \
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record              NaN
                 2024049         Vital Signs Record               20
                 2237669         Vital Signs Record               20
                 2396155         Vital Signs Record               20
                 2480434         Vital Signs Record               20
...                                                              ...
1326  1472363    9805481         Vital Signs Record              NaN
1327  1472363    9805481         Vital Signs Record              NaN
1328  1472363    9805481         Vital Signs Record              NaN
1329  1472363    9805481         Vital Signs Record              NaN
1330  1472363    9805481         Vital Signs Record              NaN

ResultItemName                                      Systolic BP Temperature  \
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record         155         NaN
                 2024049         Vital Signs Record         131         NaN
                 2237669         Vital Signs Record         130         NaN
                 2396155         Vital Signs Record         107         NaN
                 2480434         Vital Signs Record         134         NaN
...                                                         ...         ...
1326  1472363    9805481         Vital Signs Record         NaN         NaN
1327  1472363    9805481         Vital Signs Record         NaN         NaN
1328  1472363    9805481         Vital Signs Record         NaN         NaN
1329  1472363    9805481         Vital Signs Record         NaN         NaN
1330  1472363    9805481         Vital Signs Record         NaN         NaN

ResultItemName                                      Waistline Weight
LabNo PatientUID PatientVisitUID OrderItemName
1     2299       0               Vital Signs Record        68   45.4
                 2024049         Vital Signs Record       NaN     46
                 2237669         Vital Signs Record       NaN   45.8
                 2396155         Vital Signs Record       NaN     45
                 2480434         Vital Signs Record       NaN   41.1
...                                                       ...    ...
1326  1472363    9805481         Vital Signs Record       NaN    NaN
1327  1472363    9805481         Vital Signs Record       NaN    NaN
1328  1472363    9805481         Vital Signs Record       NaN    NaN
1329  1472363    9805481         Vital Signs Record       NaN    NaN
1330  1472363    9805481         Vital Signs Record       NaN    NaN

[1233971 rows x 18 columns]

In [12]:
# Reset the index if you want to move the grouped columns back to regular columns
#pivot_table_reset = pivot_table.reset_index()
#pivot_reset = pivot.reset_index()

### **Test Lab**

In [13]:
lab

,LabNo,PatientUID,PatientVisitUID,Location,RequestItemName,ResultItemName,CWhen,ResultDttm,ResultValue,Unit,ReferenceRange
0,1,2299,2024049,‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ô‡∏¥‡∏ß‡πÄ‡∏Ñ‡∏•‡∏µ‡∏¢‡∏£‡πå (OPD)-D15,BMD LUMBAR,Formatted Result,2558-02-19 16:16:51.423,NaN,FT,NaN,NaN
1,1,2299,2024049,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"ALBUMIN, 32403","ALBUMIN, 32403",2558-02-19 10:32:20.907,NaN,4.1,NaN,3.8 - 5.4
2,1,2299,2024049,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,Alkaline Phos,"ALP, 32309",2558-02-19 10:32:21.610,NaN,44,NaN,42 - 121
3,1,2299,2024049,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"ALT, 32311","ALT, 32311",2558-02-19 10:32:21.390,NaN,17,NaN,4 - 36
4,1,2299,2024049,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"AST, 32310","AST, 32310",2558-02-19 10:32:21.500,NaN,23,NaN,12 - 32
...,...,...,...,...,...,...,...,...,...,...,...
21641153,601,822860,5140446,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,Dextrostix(POCT),DTX(POCT),2561-10-19 11:00:42.207,NaN,228,mg/dL,-
21641156,602,822860,5140446,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,Dextrostix(POCT),DTX(POCT),2561-10-19 17:24:45.417,NaN,240,mg/dL,-
21641159,603,822860,5140446,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,Dextrostix(POCT),DTX(POCT),2561-10-19 22:40:42.073,NaN,171,mg/dL,-
21641162,604,822860,5140446,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,Dextrostix(POCT),DTX(POCT),2561-10-20 05:39:12.677,NaN,191,mg/dL,-
21641165,605,822860,5140446,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,Dextrostix(POCT),DTX(POCT),2561-10-20 10:53:23.537,NaN,308,mg/dL,-

In [14]:
import pandas as pd

# Replace the link with your Google Sheets CSV link for the specific sheet
sheet_link = "https://docs.google.com/spreadsheets/d/1b3VqChmx_Ezb5BCC97Pe3EEmCKFubSIQCsSBre5z8_M/gviz/tq?tqx=out:csv&sheet=Lab"

# Read the CSV file directly into a Pandas DataFrame
df = pd.read_csv(sheet_link)

# Now you have your data in a Pandas DataFrame
df

,Unnamed: 0,Location,ResultItemName,RequestItemName,Count
0,0,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"CREATININE, 32202",CREATININE,464626
1,1,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,eGFR(CKD-EPI) age >=18,CREATININE,435208
2,2,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"POTASSIUM, 32103",POTASSIUM,399456
3,3,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"BUN, 32201",BUN,388865
4,4,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"BICARBONATE, 32105",BICARBONATE,386526
...,...,...,...,...,...
2985,2985,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏†‡∏π‡∏°‡∏¥‡∏Ñ‡∏∏‡πâ‡∏°‡∏Å‡∏±‡∏ô‡∏ß‡∏¥‡∏ó‡∏¢‡∏≤‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å,"MUMP IGM, 36650",MUMP IGM,1
2986,2986,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏†‡∏π‡∏°‡∏¥‡∏Ñ‡∏∏‡πâ‡∏°‡∏Å‡∏±‡∏ô‡∏ß‡∏¥‡∏ó‡∏¢‡∏≤‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å,"MUMP IGM, 36650","MUMP IGM, 36650",1
2987,2987,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏†‡∏π‡∏°‡∏¥‡∏Ñ‡∏∏‡πâ‡∏°‡∏Å‡∏±‡∏ô‡∏ß‡∏¥‡∏ó‡∏¢‡∏≤‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å,Microsomal Ab,Microsomal Ab,1
2988,2988,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏†‡∏π‡∏°‡∏¥‡∏Ñ‡∏∏‡πâ‡∏°‡∏Å‡∏±‡∏ô‡∏ß‡∏¥‡∏ó‡∏¢‡∏≤‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å,Mosquito,i71 Mosquito(Specific IgE),1
2989,2989,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏†‡∏π‡∏°‡∏¥‡∏Ñ‡∏∏‡πâ‡∏°‡∏Å‡∏±‡∏ô‡∏ß‡∏¥‡∏ó‡∏¢‡∏≤‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å,FSH 120 min,FSH 120 min,1

In [15]:
a = df[df['Count']>=100000]
a

,Unnamed: 0,Location,ResultItemName,RequestItemName,Count
0,0,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"CREATININE, 32202",CREATININE,464626
1,1,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,eGFR(CKD-EPI) age >=18,CREATININE,435208
2,2,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"POTASSIUM, 32103",POTASSIUM,399456
3,3,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"BUN, 32201",BUN,388865
4,4,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"BICARBONATE, 32105",BICARBONATE,386526
...,...,...,...,...,...
56,56,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡πÄ‡∏Ñ‡∏°‡∏µ‡∏Ñ‡∏•‡∏¥‡∏ô‡∏¥‡∏Å ‡πÄ‡∏ß‡∏ä‡∏®‡∏≤‡∏™‡∏ï‡∏£‡πå‡∏ä‡∏±‡∏ô‡∏™‡∏π‡∏ï‡∏£,"DIRECT BILIRUBIN, 32207",DIRECT BILIRUBIN,128979
57,57,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏à‡∏∏‡∏•‡∏ó‡∏£‡∏£‡∏®‡∏ô‡πå‡∏ß‡∏¥‡∏ô‡∏¥‡∏à‡∏â‡∏±‡∏¢,Slide No.,Complete blood count,125066
58,58,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏à‡∏∏‡∏•‡∏ó‡∏£‡∏£‡∏®‡∏ô‡πå‡∏ß‡∏¥‡∏ô‡∏¥‡∏à‡∏â‡∏±‡∏¢,SQ-Epi,Urinalysis,119335
59,59,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏à‡∏∏‡∏•‡∏ó‡∏£‡∏£‡∏®‡∏ô‡πå‡∏ß‡∏¥‡∏ô‡∏¥‡∏à‡∏â‡∏±‡∏¢,PT,PT/INR,101035
60,60,‡∏´‡πâ‡∏≠‡∏á‡∏õ‡∏è‡∏¥‡∏ö‡∏±‡∏ï‡∏¥‡∏Å‡∏≤‡∏£‡∏à‡∏∏‡∏•‡∏ó‡∏£‡∏£‡∏®‡∏ô‡πå‡∏ß‡∏¥‡∏ô‡∏¥‡∏à‡∏â‡∏±‡∏¢,INR,PT/INR,100291

In [16]:
a['RequestItemName'].unique()

array(['CREATININE', 'POTASSIUM', 'BUN', 'BICARBONATE', 'SODIUM',
       'CHLORIDE', 'Dextrostix(POCT)', 'Complete blood count', 'ALBUMIN',
       'CHOLESTEROL', 'ALT', 'AST', 'Urinalysis', 'Alkaline Phos',
       'LDL-CHOL', 'SUGAR IN NAF-PLASMA', 'CALCIUM', 'PHOSPHORUS',
       'HB A1C', 'TRIGLYCERIDE', 'HDL-C', 'MAGNESIUM', 'Globulin',
       'TOTAL PROTEIN', 'TOTAL BILIRUBIN', 'DIRECT BILIRUBIN', 'PT/INR'],
      dtype=object)

In [17]:
import pandas as pd

# Assuming 'lab' is a DataFrame containing your data
# Columns: ['LabNo', 'PatientUID', 'PatientVisitUID', 'OrderItemName', 'ResultItemName', 'ResultValue', 'CWhen']

# Select the items with more than 100000 rows
selected_items = ['CREATININE', 'POTASSIUM', 'BUN', 'BICARBONATE', 'SODIUM',
                  'CHLORIDE', 'Dextrostix(POCT)', 'Complete blood count', 'ALBUMIN',
                  'CHOLESTEROL', 'ALT', 'AST', 'Urinalysis', 'Alkaline Phos',
                  'LDL-CHOL', 'SUGAR IN NAF-PLASMA', 'CALCIUM', 'PHOSPHORUS',
                  'HB A1C', 'TRIGLYCERIDE', 'HDL-C', 'MAGNESIUM', 'Globulin',
                  'TOTAL PROTEIN', 'TOTAL BILIRUBIN', 'DIRECT BILIRUBIN', 'PT/INR']

# Filter the DataFrame based on the selected items
filtered_lab = lab[lab['RequestItemName'].isin(selected_items)]

# Use pivot_table to pivot the DataFrame
pivot_table1 = filtered_lab.pivot_table(index=['LabNo', 'PatientUID', 'PatientVisitUID'], columns='RequestItemName', values='ResultValue', aggfunc='first')
pivot_table1

RequestItemName                  ALBUMIN  ALT  AST Alkaline Phos BICARBONATE  \
LabNo PatientUID PatientVisitUID
1     2299       2024049             NaN  NaN  NaN            44         NaN
                 2381054             NaN  NaN  NaN            47         NaN
                 2499619             NaN  NaN  NaN           NaN         NaN
                 2534514             NaN  NaN  NaN            50         NaN
                 2706070             NaN  NaN  NaN           NaN         NaN
...                                  ...  ...  ...           ...         ...
601   822860     5140446             NaN  NaN  NaN           NaN         NaN
602   822860     5140446             NaN  NaN  NaN           NaN         NaN
603   822860     5140446             NaN  NaN  NaN           NaN         NaN
604   822860     5140446             NaN  NaN  NaN           NaN         NaN
605   822860     5140446             NaN  NaN  NaN           NaN         NaN

RequestItemName                   BUN CALCIUM CHLORIDE CHOLESTEROL CREATININE  \
LabNo PatientUID PatientVisitUID
1     2299       2024049          NaN     NaN      NaN         NaN        NaN
                 2381054          NaN     NaN      NaN         NaN        NaN
                 2499619          NaN     NaN      NaN         NaN        NaN
                 2534514          NaN     NaN      NaN         NaN        NaN
                 2706070          NaN     NaN      NaN         195        NaN
...                               ...     ...      ...         ...        ...
601   822860     5140446          NaN     NaN      NaN         NaN        NaN
602   822860     5140446          NaN     NaN      NaN         NaN        NaN
603   822860     5140446          NaN     NaN      NaN         NaN        NaN
604   822860     5140446          NaN     NaN      NaN         NaN        NaN
605   822860     5140446          NaN     NaN      NaN         NaN        NaN

RequestItemName                   ... MAGNESIUM PHOSPHORUS POTASSIUM PT/INR  \
LabNo PatientUID PatientVisitUID  ...
1     2299       2024049          ...       NaN        NaN       NaN    NaN
                 2381054          ...       NaN        NaN       NaN    NaN
                 2499619          ...       NaN        NaN       NaN    NaN
                 2534514          ...       NaN        NaN       NaN    NaN
                 2706070          ...       NaN        NaN       NaN    NaN
...                               ...       ...        ...       ...    ...
601   822860     5140446          ...       NaN        NaN       NaN    NaN
602   822860     5140446          ...       NaN        NaN       NaN    NaN
603   822860     5140446          ...       NaN        NaN       NaN    NaN
604   822860     5140446          ...       NaN        NaN       NaN    NaN
605   822860     5140446          ...       NaN        NaN       NaN    NaN

RequestItemName                  SODIUM SUGAR IN NAF-PLASMA TOTAL BILIRUBIN  \
LabNo PatientUID PatientVisitUID
1     2299       2024049            NaN                 NaN             NaN
                 2381054            NaN                 NaN             NaN
                 2499619            NaN                 NaN             NaN
                 2534514            NaN                 NaN             NaN
                 2706070            NaN                 NaN             NaN
...                                 ...                 ...             ...
601   822860     5140446            NaN                 NaN             NaN
602   822860     5140446            NaN                 NaN             NaN
603   822860     5140446            NaN                 NaN             NaN
604   822860     5140446            NaN                 NaN             NaN
605   822860     5140446            NaN                 NaN             NaN

RequestItemName                  TOTAL PROTEIN TRIGLYCERIDE Urinalysis
LabNo PatientUID PatientVisitUID
1     2299       2024049                   NaN          NaN        NaN
                 2381054                   NaN          NaN        Neg
                 2499619                   NaN          NaN        Neg
                 2534514                   NaN          NaN        NaN
                 2706070                   NaN           67        NaN
...                                        ...          ...        ...
601   822860     5140446                   NaN          NaN        NaN
602   822860     5140446                   NaN          NaN        NaN
603   822860     5140446                   NaN          NaN        NaN
604   822860     5140446                   NaN          NaN        NaN
605   822860     5140446                   NaN          NaN        NaN

[891673 rows x 26 columns]